### ISSUE TITLE
Action fails on Ruby 2.7

### ISSUE THREAD

**Issue by jgarber623** [rubygems/release-gem#1]
First off, thank you so much for this Action. It's going to simplify and make more secure gem publishing. So great to see this land alongside [trusted publishing](https://blog.rubygems.org/2023/12/14/trusted-publishing.html).

So, the issue title here kinda gives it away and _yes_ I know Ruby 2.7 is EOL'ed, so I'd completely understand if this issue gets closed as "won't fix" or similar.

But, I found a bug and felt it worth noting:

## Description

I used the release-gem action this evening to publish a new version (0.2.1) of [sprockets-sass_embedded](https://github.com/jgarber623/sprockets-sass_embedded) to RubyGems. The job log is [available here](https://github.com/jgarber623/sprockets-sass_embedded/actions/runs/7229561547/job/19700574481)

The release-gem successfully pushed the gem to RubyGems ( 🎉 ) but then failed on the follow-up step ( 😭 ):

```
sprockets-sass_embedded 0.2.1 built to pkg/sprockets-sass_embedded-0.2.1.gem.
Tag v0.2.1 has already been created.
Pushing gem to https://rubygems.org...
Successfully registered gem: sprockets-sass_embedded (0.2.1)
Pushed sprockets-sass_embedded 0.2.1 to rubygems.org
Run gem exec rubygems-await pkg/*.gem
  gem exec rubygems-await pkg/*.gem
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    RUBYGEMS_API_KEY: ***
    BUNDLE_GEM__PUSH_KEY: ***
    GEM_HOST_API_KEY: ***
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command exec
```

I suppose that's not terribly surprising that the `gem exec` command doesn't exist under Ruby 2.7.8 and whichever version of RubyGems is installed.

**So, my question is:** Is there anything I could or should do (besides update my gem's minimum Ruby version) to do to accommodate or account for the `gem exec` error?

Thanks for your help and consideration!

### Workflow

(from [publish.yml](https://github.com/jgarber623/sprockets-sass_embedded/blob/main/.github/workflows/publish.yml))

```yaml
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
  publish-to-rubygems:
    name: Publish to RubyGems
    permissions:
      contents: write
      id-token: write
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: rubygems/release-gem@v1
```

**Comment by matthew-macgregor** [comment]
The `setup-ruby` action is pulling from the `.ruby-version` file (according to the Action's logs and the docs for `setup-ruby`). By default, `setup-ruby` also uses the RubyGems version that ships with that version of Ruby, [but you can override this](https://github.com/ruby/setup-ruby/blob/af848b40be8bb463a751551a1180d74782ba8a72/action.yml#L11) with another input.

It looks like RubyGems *just* (yesterday?) dropped suppport for Ruby 2.6, 2.7 in [v3.5.0](https://github.com/rubygems/rubygems/releases/tag/v3.5.0).

It looks like `gem exec` was added as an experimental feature in [v3.4.8](https://github.com/rubygems/rubygems/releases/tag/v3.4.8). So there's at least hypothetical overlap in the support for Ruby 2.7 and `gem exec`.

As a _workaround_, could you pin `rubygems: 3.4.22` to in the `setup-ruby` step but leave your `.ruby-version` at 2.7.8?

```yaml
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          rubygems: 3.4.22
```

This seems like it _should_ resolve the missing `gem exec` and still use the last version of RubyGems with Ruby 2.7 support. (I have not actually tried the workaround, though.)

**Comment by jgarber623** [comment]
@matthew-macgregor Thank you for the insight and thoughtful reply! Much appreciated. I'll give the configuration you put together a shot and see how it goes.

**Comment by jgarber623** [comment]
@matthew-macgregor Following up on your proposed solution, I ran the following in a Docker container (the `ruby:2.7.8` image) as a local test:

```sh
# Update to the "latest" RubyGems
$ gem update --system 3.4.22

# Test out `gem exec`
$ gem exec --help

Usage: gem exec [options --] COMMAND [args] [options]
etc. etc. etc.

# Try out rubygems-await
$ gem exec rubygems-await

ERROR:  Error installing rubygems-await:
	rubygems-await-0.4.1 requires Ruby version >= 3.0. The current ruby version is 2.7.8.
```

😭 

Confirmed on [the rubygems-await gem's RubyGems page](https://rubygems.org/gems/rubygems-await) that the latest version requires Ruby `>= 3.0`. `v0.1.x` versions required `>= 3.2`, but that seems to have changed from `v0.3.0` onward.

## A Solution!

I _just_ discovered in this project's `action.yml` that the Action accepts two (as of this writing undocumented) inputs, one of which is [`await-release`](https://github.com/rubygems/release-gem/blob/035c7c1c1c14d277318867ced5037926d2395300/action.yml#L4C3-L7):

```yaml
await-release:
    description: "Whether to poll for the release to be available on RubyGems.org"
    required: false
    default: "true"
```

So, for any project using Ruby < 3, I believe you could configure the job step like:

```yaml
- uses: rubygems/release-gem@v1
  with:
    await-release: false
```

Of course, you'd miss out on the utility of that particular feature and would have to rely on other methods (notifications from RubyGems.org, for instance) to inform you that a new gem version was published.

---

For my particular case(s), I'll likely go the route of setting `await-release: false` for any of my gems (none of which are all that widely used) that are still baselined at Ruby 2.7.

I'll leave this issue open for a bit in case there's more to add, new discoveries or ideas, or if Samuel wants to weigh in.

**Comment by ccutrer** [comment]
Did setting `await-release: false` work for you? For me, it still tried to execute the wait step.

EDIT: never mind, I see #4 now.

**Comment by jgarber623** [comment]
I'm gonna go ahead and close this one out now that:

1. There's a workaround (see [my comment above](#issuecomment-1858849901)), and
2. #4 was merged, resolving an issue with this action's handling of boolean values.

In summation, if you're using older versions of Ruby and/or RubyGems, you can avoid the errors documented above by passing `await-release: false` in your workflow's job step:

```yaml
- uses: rubygems/release-gem@v1
  with:
    await-release: false
```
